[server]
port = 8501
address = "localhost"
runOnSave = true
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[theme]
primaryColor = "#004D98"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[runner]
fastReruns = true
maxCachedMessageAge = 300

[client]
toolbarMode = "minimal"
showErrorDetails = true 